global using Azure;
global using Azure.Communication.Email;
global using AppVerse.Service.AzureCommunicationSevice;
global using AppVerse.Services;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using System.Text;
